### ISSUE TITLE
invalid memory access in linux_kqueue_cleanup()

### ISSUE THREAD

**Issue by mheily** [mheily/libkqueue#70]
src/linux/platform.c contains an out-of-bounds memory access.

Here's the buggy code:
```
    if (kq->pipefd[0] > 0) {
        close(kq->pipefd[0]);
        kq->pipefd[0] = -1;
    }

    fd_map[kq->pipefd[0]] = 0;
```

**Comment by arr2036** [comment]
Under which conditions?

**Comment by mheily** [comment]
When kq->pipefd[0] is greater than zero:
```
kq->pipefd[0] = -1;
fd_map[-1] = 0;
```
I found this when running the testsuite with AddressSanitizer.

```
==13441==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6290000001fc at pc 0x7f42f6787b10 bp 0x7f42f2cfc2e0 sp 0x7f42f2cfc2d0
WRITE of size 4 at 0x6290000001fc thread T1
    #0 0x7f42f6787b0f in linux_kqueue_cleanup /home/mark/proj/libkqueue/src/linux/platform.c:322
    #1 0x7f42f6787e6d in monitoring_thread_start /home/mark/proj/libkqueue/src/linux/platform.c:147
    #2 0x7f42f5d696da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
    #3 0x7f42f64ae88e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x12188e)

0x6290000001fc is located 4 bytes to the left of 16384-byte region [0x629000000200,0x629000004200)
allocated by thread T1 here:
    #0 0x7f42f6a71d38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
    #1 0x7f42f6787c21 in monitoring_thread_start /home/mark/proj/libkqueue/src/linux/platform.c:110
    #2 0x7f42f5d696da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)

Thread T1 created by T0 here:
    #0 0x7f42f69cad2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7f42f67877ca in linux_kqueue_start_thread /home/mark/proj/libkqueue/src/linux/platform.c:187
    #2 0x7f42f5d71826 in __pthread_once_slow (/lib/x86_64-linux-gnu/libpthread.so.0+0xf826)
```

**Comment by arr2036** [comment]
Ah, of course! Ugh, fixed.
